name: dicabs
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.7+9

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.0
  intl: ^0.18.1
  gap: ^3.0.1
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  get: ^4.6.6
  permission_handler: ^11.3.1
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.2
  geolocator: ^9.0.2
  fluttertoast: ^8.2.4
  flutter_background_service: ^5.1.0
  android_intent_plus: ^4.0.3
  flutter_local_notifications: ^17.2.1
  flutter_background_service_android: ^6.3.0



dependency_overrides:
  win32: ^5.14.0

#  background_locator_2: ^2.0.6

# flutter_icons:
#   android:true
#   ios:true
#   image_path:"assets/image/logo.jpeg"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/image/dicabs_logo.png"
